# Generated by Django 4.1.5 on 2023-02-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_scholarship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
